#!/usr/bin/env python3
import sys
import numpy as np

import matplotlib.pyplot as plt

files = sys.argv[1:]
for file in files:
    # TODO: consider np.genfromtxt
    vals = np.loadtxt(file)
    label = file if len(files) > 1 else ''
    if len(vals.shape) == 1:
        plt.plot(vals, label=label)
    elif len(vals.shape) == 1:
        xs = vals[:, 0]
        for i, ys in enumerate(vals.T[1:]):
            label += f' {i}' if vals.shape[1] > 1 else ''
            plt.plot(xs, ys, label=label)
    else:
        raise ValueError(f'To many dimensions in file: {file}, got: {vals.shape}')

plt.legend()
plt.show()
